version: '3'
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper_dataenv
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: mkobit/nifi
    container_name: nifi_dataenv
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
    volumes:
        - ./nifi/state:/opt/nifi/nifi-current/state
        - ./nifi/db:/opt/nifi/nifi-current/database_repository
        - ./nifi/flowfile:/opt/nifi/nifi-current/flowfile_repository
        - ./nifi/content:/opt/nifi/nifi-current/content_repository
        - ./nifi/provenance:/opt/nifi/nifi-current/provenance_repository
        - ./csv_data:/home/csv_data
        - ./json_data:/home/json_data

  datascience-notebook:
        image:  jupyter/minimal-notebook #datascience-notebook
        volumes:
            - ./notebooks:/home/jovyan/work
            - ./csv_data:/home/csv_data/
                
        environment:
            JUPYTER_ENABLE_LAB: "yes"
            JUPYTER_TOKEN : "psut2022"
        ports:
            - "8888:8888"
        
        container_name:   ds-jupyter
      